/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wiish_exampleapp_WiishActivity */

#ifndef _Included_org_wiish_exampleapp_WiishActivity
#define _Included_org_wiish_exampleapp_WiishActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_wiish_exampleapp_WiishActivity
 * Method:    wiish_init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_wiish_exampleapp_WiishActivity_wiish_1init
  (JNIEnv *, jobject);

/*
 * Class:     org_wiish_exampleapp_WiishActivity
 * Method:    wiish_getInitURL
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_wiish_exampleapp_WiishActivity_wiish_1getInitURL
  (JNIEnv *, jobject);

/*
 * Class:     org_wiish_exampleapp_WiishActivity
 * Method:    wiish_sendMessageToNim
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_wiish_exampleapp_WiishActivity_wiish_1sendMessageToNim
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
