[main]
version      = "0.1.0"
dst          = "dist"
resourceDir  = "resources"

[desktop]
name        = "Wiish SDL Demo"
src         = "main_desktop.nim"
# Path to an image file to use for the application icon.
# The file will automatically be converted to the correct
# format.
icon        = ""

[mobile]
name        = "WiishSDL"
src         = "main_mobile.nim"
icon        = ""

[macos]
bundle_identifier = "org.wiish.sdlexample"
category_type = "public.app-category.example"

[ios]
bundle_identifier = "org.wiish.sdlexample"
sdk_version = "" # If blank, auto-detect the latest installed version

[android]
java_package_name = "org.wiish.sdlexample"
