name: tests

on:
  pull_request:
  push:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        nimversion: 
          - stable
          # - devel
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
    env:
      WIISH_BUILD_ANDROID: yes
    steps:
    - uses: actions/checkout@v1
    - uses: iffy/install-nim@v3
      with:
        version: ${{ matrix.nimversion }}
    - name: Test
      run: |
        nimble refresh -y
        nimble install -y --depsOnly
        nimble test
    - name: Install
      run: |
        nimble install -y
        wiish init /tmp/foo
    - name: Docs
      if: runner.os == 'Linux'
      run: |
        ./builddocs.sh
    - name: Doctor
      run: |
        wiish doctor || true
