name: tests

on:
  pull_request:
  push:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    env:
      WIISH_TEST_RUN: "1"
    strategy:
      matrix:
        nimversion: 
          - stable
          # - devel
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
    steps:
    - shell: bash
      run: env | sort
    - uses: actions/checkout@v1
    - uses: iffy/install-nim@v3
      with:
        version: ${{ matrix.nimversion }}
    - name: Install
      shell: bash
      run: |
        nimble install -y
        wiish init /tmp/foo
    - name: Doctor
      shell: bash
      run: |
        wiish doctor || true
    # - name: Fix Windows path
    #   # This is needed until https://github.com/actions/virtual-environments/pull/2174/files is included in the GitHub VMs
    #   if: runner.os == 'Windows'
    #   shell: powershell
    #   run: |
    #     $ndkRoot = "C:\Program Files (x86)\Android\android-sdk\ndk-bundle"
    #     (Get-Content -Encoding UTF8 "${ndkRoot}\ndk-build.cmd").replace('%~dp0\build\ndk-build.cmd','"%~dp0\build\ndk-build.cmd"')|Set-Content "${ndkRoot}\ndk-build.cmd"
    #     type "${ndkRoot}\ndk-build.cmd"
    - name: Test
      shell: bash
      run: |
        # nim c .github/tounixpath.nim
        # normpath() {
        #   varname="$1"
        #   if [ ! -z "${!varname}" ]; then
        #     export "${1}"="$(.github/tounixpath "${!varname}")"
        #   fi
        # }
        # env | grep -i android
        # normpath ANDROID_HOME
        # normpath ANDROID_NDK_HOME
        # normpath ANDROID_NDK_PATH
        # normpath ANDROID_SDK_ROOT
        # export PATH="${ANDROID_NDK_HOME}:${PATH}"
        # export PATH="${ANDROID_SDK_ROOT}/emulator:${PATH}"
        # export PATH="${ANDROID_SDK_ROOT}/platform-tools:${PATH}"
        # echo "--------------------- build-local.mk"
        # cat "C:\Program Files (x86)\Android\android-sdk\ndk-bundle\build\\..\build\core\build-local.mk"
        # echo "---------------------"
        # env | grep -i android
        # echo $PATH
        if [ "$(uname)" == "Darwin" ] || [ "$(uname)" == "Linux" ]; then
          export WIISH_BUILD_ANDROID=yes
        fi
        wiish doctor || true
        nimble test
    - name: Docs
      if: runner.os == 'Linux'
      run: |
        ./builddocs.sh
    
