name: tests

on:
  pull_request:
  push:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    env:
      WIISH_TEST_RUN: "1"
    strategy:
      fail-fast: false
      matrix:
        nimversion: 
          - stable
          # - devel
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
    steps:
    - shell: bash
      run: env | sort
    - uses: actions/checkout@v1
    - uses: iffy/install-nim@v3
      with:
        version: ${{ matrix.nimversion }}
    - name: Install
      shell: bash
      run: |
        nimble install -y
        wiish init /tmp/foo
    - name: Doctor (Pre)
      shell: bash
      run: |
        wiish doctor || true
    - name: Install deps
      shell: bash
      run: |
        if [ "$(uname)" == "Darwin" ]; then
          brew install sdl2 sdl2_ttf sdl2_image sdl2_gfx
        elif [ "$(uname)" == "Linux" ]; then
          sudo apt-get install -y libgtk-3-dev
          sudo apt-get install -y libwebkit2gtk-4.0-dev
        else
        fi
    - name: Test
      shell: bash
      timeout-minutes: 30
      run: |
        export ANDROID_NDK_HOME="${ANDROID_SDK_ROOT}/ndk-bundle"
        export PATH="${ANDROID_NDK_HOME}:${PATH}"
        export PATH="${ANDROID_SDK_ROOT}/emulator:${PATH}"
        export PATH="${ANDROID_SDK_ROOT}/platform-tools:${PATH}"
        # nim c .github/tounixpath.nim
        # normpath() {
        #   varname="$1"
        #   if [ ! -z "${!varname}" ]; then
        #     export "${1}"="$(.github/tounixpath "${!varname}")"
        #   fi
        # }
        # env | grep -i android
        # normpath ANDROID_HOME
        # normpath ANDROID_NDK_HOME
        # normpath ANDROID_NDK_PATH
        # normpath ANDROID_SDK_ROOT
        # export PATH="${ANDROID_NDK_HOME}:${PATH}"
        # export PATH="${ANDROID_SDK_ROOT}/emulator:${PATH}"
        # export PATH="${ANDROID_SDK_ROOT}/platform-tools:${PATH}"
        # echo "--------------------- build-local.mk"
        # cat "C:\Program Files (x86)\Android\android-sdk\ndk-bundle\build\\..\build\core\build-local.mk"
        # echo "---------------------"
        # env | grep -i android
        # echo $PATH
        if [ "$(uname)" == "Darwin" ] || [ "$(uname)" == "Linux" ]; then
          export WIISH_BUILD_ANDROID=yes
        fi
        wiish doctor || true
        nimble test
    - name: Docs
      if: runner.os == 'Linux'
      run: |
        ./builddocs.sh
    
