name: tests

on:
  pull_request:
  push:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        nimversion: 
          - stable
          # - devel
        os:
          - ubuntu-latest
          # - macOS-latest
          - windows-latest
    env:
      WIISH_BUILD_ANDROID: yes
    steps:
    - shell: bash
      run: env | sort
    - uses: actions/checkout@v1
    - uses: iffy/install-nim@v3
      with:
        version: ${{ matrix.nimversion }}
    - name: Install
      shell: bash
      run: |
        nimble install -y
        wiish init /tmp/foo
    - name: Doctor
      shell: bash
      run: |
        wiish doctor || true
    - name: Test
      shell: bash
      run: |
        normpath() {
          python -c 'import os, sys; print(os.path.abspath(sys.argv[1]) if sys.argv[1] else "")' "$1"
        }
        export ANDROID_HOME="$(normpath "$ANDROID_HOME")"
        export ANDROID_NDK_HOME="$(normpath "$ANDROID_NDK_HOME")"
        export ANDROID_NDK_PATH="$(normpath "$ANDROID_NDK_PATH")"
        export ANDROID_SDK_ROOT="$(normpath "$ANDROID_SDK_ROOT")"
        env | sort
        nimble test
    - name: Docs
      if: runner.os == 'Linux'
      run: |
        ./builddocs.sh
    
